;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		beginning-of-visual-line
		c-electric-delete-forward
		c-electric-paren
		c-electric-semi&comma
		c-electric-slash
		c-electric-star
		c-indent-line-or-region
		end-of-visual-line
		helm-M-x
		helm-confirm-and-exit-minibuffer
		ignore
		ignore-preserving-kill-region
		indent-for-tab-command
		kill-region
		lsp-execute-code-action
		lsp-find-definition-mouse
		lsp-ui-doc--handle-mouse-movement
		sgml-skip-tag-forward
		sgml-slash
		wisi-case-adjust-interactive
		yaml-electric-backspace
		))

(setq mc/cmds-to-run-once
      '(
		end-of-buffer
		lsp-execute-code-action
		))
