;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		beginning-of-visual-line
		c-electric-delete-forward
		c-electric-paren
		c-electric-semi&comma
		c-indent-line-or-region
		end-of-visual-line
		helm-M-x
		helm-confirm-and-exit-minibuffer
		ignore-preserving-kill-region
		kill-region
		lsp-execute-code-action
		lsp-ui-doc--handle-mouse-movement
		))

(setq mc/cmds-to-run-once
      '(
		end-of-buffer
		lsp-execute-code-action
		))
